repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-xml
      - id: check-json
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=2"
          - "--no-sort-keys"
          - "--no-ensure-ascii"
      - id: end-of-file-fixer
        exclude: '.*\.asset$'
      - id: trailing-whitespace
        exclude: '.*\.asset$'
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
        exclude: '(client/OkeyClient/.*)|(server/OkeyServer/.*)'
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-case-conflict
      - id: detect-private-key
      - id: mixed-line-ending
  - repo:  https://github.com/milin/giticket
    rev: v1.3
    hooks:
      - id:  giticket
        args: ['--regex=\d+', '--format=GL-{ticket}: {commit_msg}', '--mode=regex_match']  # Optional
        stages: [prepare-commit-msg]
  - repo: local
    hooks:
      - id: dotnet-tool-restore
        name: Install .NET tools
        entry: dotnet tool restore
        language: system
        always_run: true
        pass_filenames: false
        stages:
          - commit
          - push
          - post-checkout
          - post-rewrite
        description: Install the .NET tools listed at .config/dotnet-tools.json.
      - id: csharpier
        name: Run CSharpier on C# files
        entry: dotnet tool run dotnet-csharpier
        language: system
        types:
          - c#
        description: CSharpier is an opinionated C# formatter inspired by Prettier.
  - repo: local
    hooks:
      - id: gitlint
        name: gitlint
        description: Checks your git commit messages for style.
        stages: [commit-msg]
        language: system
        entry: gitlint
        args: [--staged, --msg-filename]
