- hosts: all
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - git
          - git-lfs
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
          - vim
          - nano
          - screen
        state: latest
        update_cache: true
    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - docker-compose
        state: latest
        update_cache: true
    - name: Install Docker Module for Python
      pip:
        name: docker
    - name: Install ipython while we're at it
      pip:
        name: ipython
    - name: Ensure group "docker" exists
      group:
        name: docker
        state: present
    - name: Add user to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
    - name: Set Docker logging driver
      copy:
        dest: /etc/docker/daemon.json
        content: |
          {
            "log-driver": "local"
          }
    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: true
